### ISSUE TITLE
DCVCameraView component  not working

### ISSUE THREAD

**Issue by MichaelHao25** [Dynamsoft/capture-vision-react-native#25]
The first time you open it, you can scan, then return to the desktop, and the application becomes the background, and then the camera cannot be displayed
one ：
<img width="356" alt="image" src="https://user-images.githubusercontent.com/20773235/197348776-22c98fdd-b183-4ce0-8015-224904693ccd.png">
two:
<img width="219" alt="image" src="https://user-images.githubusercontent.com/20773235/197348821-6d162bc7-6c26-4d85-a799-e90f287d56ca.png">

**Comment by MichaelHao25** [comment]
???

**Comment by Dynamsoft-Jerson** [comment]
Thanks for your feedback. We recently fixed a similar bug on DCV RN v1.1.7. Is your project based on v1.1.7?

**Comment by MichaelHao25** [comment]
> Thanks for your feedback. We recently fixed a similar bug on DCV RN v1.1.7. Is your project based on v1.1.7?

yes

**Comment by MichaelHao25** [comment]
> Thanks for your feedback. We recently fixed a similar bug on DCV RN v1.1.7. Is your project based on v1.1.7?

When will it be released?

**Comment by MichaelHao25** [comment]
> Thanks for your feedback. We recently fixed a similar bug on DCV RN v1.1.7. Is your project based on v1.1.7?

new version publish time ?

**Comment by Dynamsoft-Jerson** [comment]
https://github.com/Dynamsoft/capture-vision-react-native-samples/issues/3
The above bug has been fixed in v1.1.7.  We tested the scenario you mentioned and did not reproduce the problem. Is it convenient to provide your sample code and some environment information?

React-Native version
Platform used (iOS, Android, etc.) ideally including the OS version.
Device model used (e.g. iPhone X, Samsung Galaxy S9)

**Comment by MichaelHao25** [comment]
Platform Android（9）
Device ：vivo y3 （V1901A）
React-native version：0.63

**Comment by MichaelHao25** [comment]
More device information is being collected ，but React-Native version unification 0.63

**Comment by MichaelHao25** [comment]
Platform Android（10）
Device ：huawei HoNOR 9X （HLK-AL00）

**Comment by Dynamsoft-Jerson** [comment]
Do you use react-navigation for page switching? Can you provide your code snippet for page switching?
