### ISSUE TITLE
CocoaPods could not find compatible versions for pod "DynamsoftBarcodeReader"

### ISSUE THREAD

**Issue by oktalk** [Dynamsoft/capture-vision-react-native#28]
I'm trying to add this barcode scanner to an existing React Native project. After running `yarn && npx pod-install ios` here is the error I get:

```
[!] CocoaPods could not find compatible versions for pod "DynamsoftBarcodeReader":
  In Podfile:
    dynamsoft-capture-vision-react-native (from `../node_modules/dynamsoft-capture-vision-react-native`) was resolved to 1.1.7, which depends on
      DynamsoftBarcodeReader (= 9.2.13)

    vision-camera-dynamsoft-barcode-reader (from `../node_modules/vision-camera-dynamsoft-barcode-reader`) was resolved to 0.6.0, which depends on
      DynamsoftBarcodeReader (= 9.4.0)
```

###Packages
"react-native": "0.67.1",
"dynamsoft-capture-vision-react-native": "^1.1.7",

Any ideas on how to handle this?

**Comment by apb-hello-world** [comment]
Try uninstalling `vision-camera-dynamsoft-barcode-reader` and then running a pod install. They both have DynamsoftBarcodeReader as dependencies, but at different versions.

**Comment by Sir-kof** [comment]
Just go into the archive "node_modules/dynamsoft-capture-vision-react-native/dynamsoft-capture-vision-react-native.podspec" and update DynamsoftBarcodeReader version to 9.4.0 and run pod install again.
