### ISSUE TITLE
Document scanner

### ISSUE THREAD

**Issue by NadeemKhanFh** [Dynamsoft/capture-vision-react-native#31]
Hi @Dynamsoft-Henry can we scan documents using this sdk on ios and android, if not, do you guys have any plan to support this feature.

**Comment by Dynamsoft-Henry** [comment]
Hi @NadeemKhanFh 

I'm sorry that the document-scanning feature is only available for native Android and iOS SDKs, Xamarin.Forms but not available for React Native.

There will be a significant upgrade in a few months or at the latest half a year. After the significant upgrade, document-scanning features will be available for React Native SDK.

Native Android & iOS document scanning: 

[https://github.com/Dynamsoft/document-normalizer-mobile-samples](url)

Xamarin.Forms document scanning:

[https://github.com/Dynamsoft/document-normalizer-xamarin-forms-samples](url)

**Comment by xulihang** [comment]
There is a React Native Vison Camera Frame Processor plugin for Dynamsoft Document Normalizer which you can use for now: https://github.com/tony-xlh/vision-camera-dynamsoft-document-normalizer

**Comment by AleksandrTermenzhy** [comment]
Hey @Dynamsoft-Henry,

Sorry for posting to this closed thread, just didn't want to duplicate the issue. So I wanted to ask if there any changes in Dynamsoft's plans on bringing the full-featured Capture Vision to React Native? I'm specifically interested in Document Normalizer.

P.S. I really appreciate what @xulihang has done with the plugin for vision camera. But unfortunately the basic library is very unstable itself and it's a real pain to maintain it.

**Comment by Dynamsoft-Henry** [comment]
Hi @AleksandrTermenzhy 

capture-vision react native version 2.x is under development. Document scanning features will be included. We will first release a new version with the barcode decoding feature and add document scanning features later this year.
